// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package db

import (
	"context"
)

const addURL = `-- name: AddURL :one
INSERT INTO urls (id, url)
VALUES (?1, ?2)
ON CONFLICT(url) DO UPDATE SET
    updated_at = CURRENT_TIMESTAMP
RETURNING id, url, created_at, updated_at
`

type AddURLParams struct {
	ID  string
	Url string
}

func (q *Queries) AddURL(ctx context.Context, arg AddURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, addURL, arg.ID, arg.Url)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE url = ?1
`

func (q *Queries) DeleteURL(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, deleteURL, url)
	return err
}

const getURL = `-- name: GetURL :one
SELECT id, url, created_at, updated_at FROM urls
WHERE url = ?1
`

func (q *Queries) GetURL(ctx context.Context, url string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURL, url)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listURLs = `-- name: ListURLs :many
SELECT id, url, created_at, updated_at FROM urls
ORDER BY updated_at DESC
`

func (q *Queries) ListURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
