# Config file for Air

# Root directory of your project
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  args_bin = ["start_server"]
  exclude = ["tmp/*" ,  "client/*", "db/*"]
  include = ["**/*.go"]
  ignore = ["tmp/*"]
  poll = true
  send_interrupt = true   # forwards SIGINT to the child process
  kill_delay = "5s" # wait this long before force killing the app

[log]
  level = "debug"

[watcher]
  color = true
  debounce = 1000
  ignore = ["tmp/*", "vendor/*", "db/*"]

[misc]
clean_on_exit = true