// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"
	"database/sql"
)

const addCredential = `-- name: AddCredential :one
INSERT INTO credentials (id, url, form_input_id, form_input_name, form_input_type, form_input_val)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (url, form_input_id)
DO UPDATE SET
  form_input_name = excluded.form_input_name,
  form_input_type = excluded.form_input_type,
  form_input_val = excluded.form_input_val
RETURNING id, url, form_input_id, form_input_name, form_input_type, form_input_val, created_at, updated_at
`

type AddCredentialParams struct {
	ID            string
	Url           string
	FormInputID   string
	FormInputName sql.NullString
	FormInputType string
	FormInputVal  string
}

func (q *Queries) AddCredential(ctx context.Context, arg AddCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, addCredential,
		arg.ID,
		arg.Url,
		arg.FormInputID,
		arg.FormInputName,
		arg.FormInputType,
		arg.FormInputVal,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.FormInputID,
		&i.FormInputName,
		&i.FormInputType,
		&i.FormInputVal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredentials = `-- name: DeleteCredentials :exec
DELETE FROM credentials
WHERE url = ?1 OR id = ?2
`

type DeleteCredentialsParams struct {
	Url string
	ID  string
}

func (q *Queries) DeleteCredentials(ctx context.Context, arg DeleteCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, deleteCredentials, arg.Url, arg.ID)
	return err
}

const getCredentials = `-- name: GetCredentials :many
SELECT id, url, form_input_id, form_input_name, form_input_type, form_input_val, created_at, updated_at FROM credentials
WHERE url = ?1 OR id = ?2
`

type GetCredentialsParams struct {
	Url string
	ID  string
}

func (q *Queries) GetCredentials(ctx context.Context, arg GetCredentialsParams) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentials, arg.Url, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.FormInputID,
			&i.FormInputName,
			&i.FormInputType,
			&i.FormInputVal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET
  form_input_id = ?1,
  form_input_name = ?2,
  form_input_type = ?3,
  form_input_val = ?4
WHERE url = ?5
RETURNING id, url, form_input_id, form_input_name, form_input_type, form_input_val, created_at, updated_at
`

type UpdateCredentialParams struct {
	FormInputID   string
	FormInputName sql.NullString
	FormInputType string
	FormInputVal  string
	Url           string
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential,
		arg.FormInputID,
		arg.FormInputName,
		arg.FormInputType,
		arg.FormInputVal,
		arg.Url,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.FormInputID,
		&i.FormInputName,
		&i.FormInputType,
		&i.FormInputVal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
