// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Credential struct {
	ID            string
	Url           string
	FormInputID   string
	FormInputName sql.NullString
	FormInputType string
	FormInputVal  string
	CreatedAt     string
	UpdatedAt     string
}

type Url struct {
	ID        string
	Url       string
	CreatedAt string
	UpdatedAt string
}
